### ISSUE TITLE
EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE

### ISSUE THREAD

**Issue by emuthomi** [kiwi-bop/flutter_signature_pad#3] opened 2019-01-20 17:55 UTC
I am getting errors when I try to draw on the canvas. Furthermore, no drawing is visible until I do a change color or stroke size

```sh
E/flutter ( 9922): [ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty
Reloaded 11 of 615 libraries in 3,608ms.
I/flutter ( 9922): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 9922): The following _Exception was thrown resolving an image codec:
I/flutter ( 9922): Exception: operation failed
I/flutter ( 9922): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): change stroke width to 2
E/flutter ( 9922): [ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty
I/flutter ( 9922): Another exception was thrown: Exception: operation failed
I/flutter ( 9922): cleared
E/flutter ( 9922): [ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty
I/flutter ( 9922): Another exception was thrown: Exception: operation failed
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 9922): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
```
That's the log, it doesn't even specify where the error is coming from.

**Comment by jaumard** [comment] 2019-01-20 18:12
Do you get this with the example app ?

**Comment by emuthomi** [comment] 2019-01-20 18:15
No, in my app code. Let me run the example app and see.

**Comment by jaumard** [comment] 2019-01-20 18:17
Having a way to reproduce would be nice !  because here it look like it crash in C code of flutter so can't really do something about this ^^
Also what version of flutter do you use ? Can you put the `doctor -v` output please.

**Comment by emuthomi** [comment] 2019-01-20 18:30
> Having a way to reproduce would be nice ! because here it look like it crash in C code of flutter so can't really do something about this ^^
> Also what version of flutter do you use ? Can you put the `doctor -v` output please.

Here is output if flutter doctor

```sh
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    X Android license status unknown.
[!] Android Studio (version 2.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to find bundled Java version.
[√] VS Code, 32-bit edition (version 1.30.1)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

```

**Comment by jaumard** [comment] 2019-01-20 18:34
Thanks ! I'm using flutter v1.0.0 and have not this kind of crash... I'll try to test on several devices during the week see if I can reproduce or not... 
And you having the crash when you try to draw on the screen or when you try to save the image ?

**Comment by emuthomi** [comment] 2019-01-20 18:38
When drawing on the screen. All those `I/flutter (25107): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
` happen when I attempt to draw. 

And then you can see this Exception below happens after changing color or stroke width:

```
I/flutter (25107): change stroke width to 1
E/flutter (25107): [ERROR:flutter/lib/ui/painting/codec.cc(91)] InitCodec failed - buffer was empty
I/flutter (25107): Another exception was thrown: Exception: operation failed

```

**Comment by emuthomi** [comment] 2019-01-20 18:39
Let me also try to fiddle with it and see what's up. Thanks for this wonderful library.

**Comment by jaumard** [comment] 2019-01-20 18:41
I was able to reproduce on my android emulator ! I'll try to find what append and fix it :) but for now no clue what happen lol

**Comment by jaumard** [comment] 2019-01-20 18:46
Can you try with the master branch please ? I think I found the problem and I've pushed a fix :)

**Comment by emuthomi** [comment] 2019-01-20 18:55
This now works in the example app. Let me try in my code and  see.

**Comment by emuthomi** [comment] 2019-01-20 19:13
I can confidently report this issue is resolved. Thank you very much for the quick response.

**Comment by jaumard** [comment] 2019-01-20 19:14
Nice ! Thanks for the report and testing ! I'll publish this now under 0.2.3 :)

**Closed by jaumard** 2019-01-20 19:14 UTC

**Comment by emuthomi** [comment] 2019-01-20 19:16
BTW, what's that blue dot in the middle of the canvas, can it be removed?

**Comment by jaumard** [comment] 2019-01-20 19:19
It's just on the example app :) to show that you can draw yourself some kind of watermark :)

**Comment by emuthomi** [comment] 2019-01-20 19:20
> It's just on the example app :) to show that you can draw yourself some kind of watermark :)

Ah great.
